# Site Settings
title: Sangwook Blog
description: Sangwook-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: "tkddnr924"

# Build Settings
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://tkddnr924.github.io" # the base hostname & protocol for your site
markdown: kramdown