# site settings
title: Portfolio
subtitle: by 안상욱
email: tkddnr924@gmail.com
description: 안상욱의 Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Ahn Sangwook
street_address:
city: 부천
state: 경기도
zip_code:
country: 대한민국
phone: 010-2971-8061

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/sangwook924
github_url: https://github.com/tkddnr924
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/vvook924/
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
